### ISSUE TITLE
Tracking Percent Played

### ISSUE THREAD

**Issue by aervans** [mickey/videojs-ga#14]
Just out of curiosity, how are you making sense of the percent played? Based on what I'm seeing the plugin is sending the percent played as 10, 20, 30, and so on. On the google analytics side you end up with an average value based on these different events.

So let's say 3 users that watch up to 30, 40, and 50 percent. The follow values will be sent:
User 1 sends -10, 20, 30
User 2 sends 10, 20, 30, 40
User 3 sends 10, 20, 30, 40, 50

The average played for these three users should be (30+40+50)/3=40. However, what you end up with in Google Analytics is (10+20+30+10+20+30+40+10+20+30+40+50)/12=25.83 which is quite far off from what is expected.

**Comment by mickey** [comment]
Thanks for stepping in @blakerson.

**Comment by mlisle** [comment]
@blakerson Thanks for your explanation. That's exactly the type of report I'm searching for, but cannot seem to find... nor can I figure out how to create.

Could someone give some direction as to how they're making use of the percent played event in Google Analytics?

All I can manage to uncover is the average value for each event action... but as @aervans explained, that's not too helpful. 

Thanks...

**Comment by nickvitale** [comment]
@mlisle We're having the same or a similar problem. 

The values for each logged event that is 'percent played' can range from 0 to 60, to 150 or 830.  Huge numbers that make little sense as to the watching of a video even when viewing them as a percentage.

Here's an example from Google Analytics.

![image](https://cloud.githubusercontent.com/assets/5772400/9759666/ad425f28-56e6-11e5-872a-8708238dc5e5.png)

Even when use the API to get the raw data it doesn't really help. I'm fresh out of ideas.
